CREATE INDEX STOCK_IPO_IDX ON STOCK(IPO_date);
CREATE INDEX USER_NAME_IDX ON USER(name);

SELECT company_name, IPO_date FROM STOCK 
WHERE IPO_date BETWEEN "2012/01/01" AND "2020/01/01";
EXPLAIN SELECT company_name, IPO_date FROM STOCK 
WHERE IPO_date BETWEEN "2012/01/01" AND "2020/01/01";

SELECT name, email FROM USER WHERE name LIKE "F%";
EXPLAIN SELECT name, email FROM USER WHERE name LIKE "F%";
